export interface SeedComponent {
    key: string;
    displayName: string;
    category: string;
    vendor: string;
    supportedFlows: string[];
    scalingModel: string;
    failureMode: string;
    assumptions: Record<string, unknown>;
    iconPath: string;
    documentation?: string;
    isManaged: boolean;
    isExperimental: boolean;
    defaultThroughput: number;
    defaultLatency: number;
    description: string;
}

export const componentSeeds: SeedComponent[] = [
    {
        key: 'load-balancer',
        displayName: 'Load Balancer',
        category: 'NETWORKING',
        vendor: 'AWS',
        supportedFlows: ['SYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'FAIL_STOP',
        assumptions: { connectionLimit: 1000000 },
        iconPath: '/icons/load-balancer.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 50000,
        defaultLatency: 2,
        description: 'L7/L4 load balancer. Distributes traffic across instances.',
    },
    {
        key: 'api-gateway',
        displayName: 'API Gateway',
        category: 'NETWORKING',
        vendor: 'AWS',
        supportedFlows: ['SYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'BACKPRESSURE',
        assumptions: { rateLimitPerSec: 10000 },
        iconPath: '/icons/api-gateway.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 10000,
        defaultLatency: 5,
        description: 'Authentication, rate limiting, routing. Single entry point.',
    },
    {
        key: 'cdn',
        displayName: 'CDN',
        category: 'NETWORKING',
        vendor: 'CLOUDFLARE',
        supportedFlows: ['SYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'DEGRADED',
        assumptions: { cacheHitRatio: 0.9 },
        iconPath: '/icons/cdn.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 100000,
        defaultLatency: 10,
        description: 'Edge caching. Reduces origin load for static/cacheable content.',
    },
    {
        key: 'api-server',
        displayName: 'API Server',
        category: 'COMPUTE',
        vendor: 'CUSTOM',
        supportedFlows: ['SYNC', 'ASYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'FAIL_STOP',
        assumptions: { instanceMemoryMB: 512 },
        iconPath: '/icons/api-server.svg',
        isManaged: false,
        isExperimental: false,
        defaultThroughput: 1000,
        defaultLatency: 50,
        description: 'Stateless request handler. Scales horizontally.',
    },
    {
        key: 'worker',
        displayName: 'Worker',
        category: 'COMPUTE',
        vendor: 'CUSTOM',
        supportedFlows: ['ASYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'RETRY_STORM',
        assumptions: { concurrency: 10 },
        iconPath: '/icons/worker.svg',
        isManaged: false,
        isExperimental: false,
        defaultThroughput: 500,
        defaultLatency: 100,
        description: 'Async job processor. Consumes from queues.',
    },
    {
        key: 'cron-job',
        displayName: 'Cron Job',
        category: 'COMPUTE',
        vendor: 'CUSTOM',
        supportedFlows: ['BATCH'],
        scalingModel: 'FIXED',
        failureMode: 'RETRY_STORM',
        assumptions: { runIntervalSec: 60 },
        iconPath: '/icons/cron.svg',
        isManaged: false,
        isExperimental: false,
        defaultThroughput: 100,
        defaultLatency: 1000,
        description: 'Scheduled batch processing. Time-triggered execution.',
    },
    {
        key: 'kafka',
        displayName: 'Kafka',
        category: 'MESSAGING',
        vendor: 'APACHE',
        supportedFlows: ['ASYNC', 'STREAM'],
        scalingModel: 'PARTITIONED',
        failureMode: 'BACKPRESSURE',
        assumptions: { partitions: 12, replicationFactor: 3 },
        iconPath: '/icons/kafka.svg',
        isManaged: false,
        isExperimental: false,
        defaultThroughput: 100000,
        defaultLatency: 5,
        description: 'Distributed log. High-throughput pub/sub with retention.',
    },
    {
        key: 'rabbitmq',
        displayName: 'RabbitMQ',
        category: 'MESSAGING',
        vendor: 'OSS',
        supportedFlows: ['ASYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'BACKPRESSURE',
        assumptions: { queueDepth: 10000 },
        iconPath: '/icons/rabbitmq.svg',
        isManaged: false,
        isExperimental: false,
        defaultThroughput: 20000,
        defaultLatency: 3,
        description: 'Message broker. Complex routing, guaranteed delivery.',
    },
    {
        key: 'bullmq',
        displayName: 'BullMQ',
        category: 'MESSAGING',
        vendor: 'OSS',
        supportedFlows: ['ASYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'RETRY_STORM',
        assumptions: { maxRetries: 3 },
        iconPath: '/icons/bullmq.svg',
        isManaged: false,
        isExperimental: false,
        defaultThroughput: 5000,
        defaultLatency: 2,
        description: 'Redis-based job queue. Priority, delay, retry support.',
    },
    // Caching & Storage
    {
        key: 'redis',
        displayName: 'Redis',
        category: 'CACHE',
        vendor: 'REDIS',
        supportedFlows: ['SYNC'],
        scalingModel: 'SHARDED',
        failureMode: 'FAIL_STOP',
        assumptions: { maxMemoryMB: 1024 },
        iconPath: '/icons/redis.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 100000,
        defaultLatency: 1,
        description: 'In-memory KV store. Sub-ms reads, pub/sub, caching.',
    },
    {
        key: 'postgresql',
        displayName: 'PostgreSQL',
        category: 'DATABASE',
        vendor: 'POSTGRESQL',
        supportedFlows: ['SYNC'],
        scalingModel: 'VERTICAL',
        failureMode: 'FAIL_STOP',
        assumptions: { connectionPool: 100 },
        iconPath: '/icons/postgresql.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 5000,
        defaultLatency: 10,
        description: 'Relational DB. ACID, complex queries, strong consistency.',
    },
    {
        key: 'mongodb',
        displayName: 'MongoDB',
        category: 'DATABASE',
        vendor: 'MONGODB',
        supportedFlows: ['SYNC'],
        scalingModel: 'SHARDED',
        failureMode: 'DEGRADED',
        assumptions: { writeConcern: 'majority' },
        iconPath: '/icons/mongodb.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 10000,
        defaultLatency: 5,
        description: 'Document store. Flexible schema, horizontal scaling.',
    },
    // Observability
    {
        key: 'metrics',
        displayName: 'Metrics',
        category: 'OBSERVABILITY',
        vendor: 'CNCF',
        supportedFlows: ['ASYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'DEGRADED',
        assumptions: { retentionDays: 15 },
        iconPath: '/icons/metrics.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 50000,
        defaultLatency: 1,
        description: 'Time-series aggregation. Prometheus, Datadog, etc.',
    },
    {
        key: 'logs',
        displayName: 'Logs',
        category: 'OBSERVABILITY',
        vendor: 'CNCF',
        supportedFlows: ['ASYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'DEGRADED',
        assumptions: { retentionDays: 30 },
        iconPath: '/icons/logs.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 100000,
        defaultLatency: 5,
        description: 'Structured logging. ELK, Loki, Cloudwatch.',
    },
    {
        key: 'tracing',
        displayName: 'Tracing',
        category: 'OBSERVABILITY',
        vendor: 'CNCF',
        supportedFlows: ['ASYNC'],
        scalingModel: 'HORIZONTAL',
        failureMode: 'DEGRADED',
        assumptions: { samplingRate: 0.1 },
        iconPath: '/icons/tracing.svg',
        isManaged: true,
        isExperimental: false,
        defaultThroughput: 10000,
        defaultLatency: 10,
        description: 'Distributed tracing. Jaeger, Zipkin, Tempo.',
    },
];

export const categoryNames: Record<string, string> = {
    NETWORKING: 'Traffic & Networking',
    COMPUTE: 'Compute',
    MESSAGING: 'Messaging & Streaming',
    CACHE: 'Caching',
    DATABASE: 'Storage & Databases',
    OBSERVABILITY: 'Observability',
};